import axios from "axios"
const data = [
  {
    OS: "18414124",
    ABERTURA_OS: "18/08/2023 15:15:14",
    ATRIBUICAO_OS: "18/08/2023 15:17:57",
    PIB: "32123649",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "JAC01063                 ",
    MCU: "    AT320029",
    ORGAO: "RESERVA TECNICA - PE",
    DR: "32",
    DR_SIGLA: "PE ",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 32123649 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: SCANNER/CANON CTR 769/2023 -  NÃO LIGA.  PIB.32123649  -  SÉRIE:JAC01063I  ENVIAR PARA O ERP Telefone de contato: ALFREDO - (81) 2101.6642   MASIEL 2101.6670 Local de atendimento: PE/CESTI/GESTI/SLTI - AV. GUARARAPES, 250 3º ANDAR STO ANTONIO RECIFE/PE - CEP 50010-900 Informe a localidade para atendimento desta solicitação: SE/PE",
    DESCRICAO_LONGA_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 32123649 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: SCANNER/CANON CTR 769/2023 -  NÃO LIGA.  PIB.32123649  -  SÉRIE:JAC01063I  ENVIAR PARA O ERP Telefone de contato: ALFREDO - (81) 2101.6642   MASIEL 2101.6670 Local de atendimento: PE/CESTI/GESTI/SLTI - AV. GUARARAPES, 250 3º ANDAR STO ANTONIO RECIFE/PE - CEP 50010-900 Informe a localidade para atendimento desta solicitação: SE/PE; 24/08/2023 16:18:13 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 21/08/2023 11:32:00; SOLUÇÃO DO CHAMADO: Troca do equipamento através de logística reversa.. (JÉSSICA LIMA DA SILVA LARA); 24/08/2023 16:18:13 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA)",
    DESCRICAO: "Manutenção Solicitada: Scanner de Mesa  PIB: 3212364...",
    SOLUCAO: "Troca do equipamento através de logística reversa.",
    TECNICO: null,
    NOME_TECNICO: null,
    SLA: 2,
    FECHAMENTO_OS: "21/08/2023 11:33:00",
    ATRASO: "0",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "RECIFE                   ",
    AREA_CLASSIFICACAO: "PP",
    TP_ATENDIMENTO: "L",
    LIMITE_SLA: null,
  },
  {
    OS: "18449513",
    ABERTURA_OS: "28/08/2023 13:30:11",
    ATRIBUICAO_OS: "28/08/2023 13:32:30",
    PIB: "01067901",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "JAC01243                 ",
    MCU: "    00436990",
    ORGAO: "GER OPERA FISCAIS/DETRI",
    DR: "74",
    DR_SIGLA: "SPI",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 01067901 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: Botão liga e desliga do equipamento está com defeito. Telefone de contato: (14)3108-4215 Local de atendimento: R. Benedito Eleutério, 5-79 - Vila Pacifico, Bauru - SP, 17050-370 Informe a localidade para atendimento desta solicitação: SE/SPI   #####DIAGNOSTICO##### Scanner novo recebido não liga. Encaminhar para GARANTIA.",
    DESCRICAO_LONGA_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 01067901 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: Botão liga e desliga do equipamento está com defeito. Telefone de contato: (14)3108-4215 Local de atendimento: R. Benedito Eleutério, 5-79 - Vila Pacifico, Bauru - SP, 17050-370 Informe a localidade para atendimento desta solicitação: SE/SPI   #####DIAGNOSTICO##### Scanner novo recebido não liga. Encaminhar para GARANTIA.; 30/08/2023 09:50:34 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 29/08/2023 12:00:00; SOLUÇÃO DO CHAMADO: Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.. (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:50:34 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:50:49 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 29/08/2023 12:00:00; SOLUÇÃO DO CHAMADO: Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.. (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:50:49 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:51:01 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 29/08/2023 12:00:00; SOLUÇÃO DO CHAMADO: Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.. (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:51:01 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:51:37 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 29/08/2023 12:00:00; SOLUÇÃO DO CHAMADO: Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.. (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:51:37 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:52:41 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 29/08/2023 12:00:00; SOLUÇÃO DO CHAMADO: Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.. (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:52:41 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:53:37 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 29/08/2023 12:00:00; SOLUÇÃO DO CHAMADO: Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.. (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:53:37 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:54:20 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 29/08/2023 12:00:00; SOLUÇÃO DO CHAMADO: Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.. (JÉSSICA LIMA DA SILVA LARA); 30/08/2023 09:54:20 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA)",
    DESCRICAO: "Manutenção Solicitada: Scanner de Mesa  PIB: 0106790...",
    SOLUCAO:
      "Feito o reparo do botão e após o atendimento, o equipamento apresentou funcionamento normal.",
    TECNICO: null,
    NOME_TECNICO: null,
    SLA: 2,
    FECHAMENTO_OS: "29/08/2023 12:01:00",
    ATRASO: "0",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "BAURU                    ",
    AREA_CLASSIFICACAO: "GA",
    TP_ATENDIMENTO: "S",
    LIMITE_SLA: null,
  },
  {
    OS: "18450443",
    ABERTURA_OS: "29/08/2023 08:50:12",
    ATRIBUICAO_OS: "29/08/2023 08:52:10",
    PIB: "01068087",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "JAC00862                 ",
    MCU: "    00436998",
    ORGAO: "GER CADASTRO/DEGEC",
    DR: "72",
    DR_SIGLA: "SPM",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 01068087 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: Bom dia!  recebemos o novo Scaner de mesa citado , porém o memso veio com o botão de ligar quebrado, não sendo possível realizar sua instalação. solicitamos conserto , grata Telefone de contato: 43138626 Local de atendimento: Rua Mergertallher 592, 13 a Bloco 2 Informe a localidade para atendimento desta solicitação: SE/SPM",
    DESCRICAO_LONGA_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 01068087 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: Bom dia!  recebemos o novo Scaner de mesa citado , porém o memso veio com o botão de ligar quebrado, não sendo possível realizar sua instalação. solicitamos conserto , grata Telefone de contato: 43138626 Local de atendimento: Rua Mergertallher 592, 13 a Bloco 2 Informe a localidade para atendimento desta solicitação: SE/SPM; 30/08/2023 15:09:55 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 30/08/2023 15:10:35; SOLUÇÃO DO CHAMADO: IDENTIFICADO QUE O BOTÃO LIGA/DESLIGA ESTAVA DESENCAIXADO, PROVÁVEL CAUSA BALANÇO DE TRANSPORTE, TESTES OK. (RAFAEL BENTO LARA); 30/08/2023 15:09:55 Utilização de serviços e peças: . (RAFAEL BENTO LARA)",
    DESCRICAO: "Manutenção Solicitada: Scanner de Mesa  PIB: 0106808...",
    SOLUCAO:
      "IDENTIFICADO QUE O BOTÃO LIGA/DESLIGA ESTAVA DESENCAIXADO, PROVÁVEL CAUSA BALANÇO DE TRANSPORTE, TESTES OK",
    TECNICO: "30264535871",
    NOME_TECNICO: "RAFAEL BENTO LARA",
    SLA: 2,
    FECHAMENTO_OS: "30/08/2023 15:11:35",
    ATRASO: "0",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "SAO PAULO                ",
    AREA_CLASSIFICACAO: "GA",
    TP_ATENDIMENTO: "S",
    LIMITE_SLA: null,
  },
  {
    OS: "18525906",
    ABERTURA_OS: "19/09/2023 14:25:17",
    ATRIBUICAO_OS: "19/09/2023 14:28:59",
    PIB: "30043886",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "21JAC01835               ",
    MCU: "    00437420",
    ORGAO: "SEC AVAL CONT INTERNO/SGCIN",
    DR: "30",
    DR_SIGLA: "PB ",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 30043886 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: porta usb do mini pc nao reconhece scaneer após troca da placa mãe.  Telefone de contato: 8332163623 Local de atendimento: COA 1 andar João Pessoa PB Informe a localidade para atendimento desta solicitação: SE/PB   #####DIAGNOSTICO##### ==> Problema no scanner. Liga mas não funciona  não funciona em porta alguma. Mas as portas USB's funcionam com outros periféricos.",
    DESCRICAO_LONGA_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 30043886 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: porta usb do mini pc nao reconhece scaneer após troca da placa mãe.  Telefone de contato: 8332163623 Local de atendimento: COA 1 andar João Pessoa PB Informe a localidade para atendimento desta solicitação: SE/PB   #####DIAGNOSTICO##### ==> Problema no scanner. Liga mas não funciona  não funciona em porta alguma. Mas as portas USB's funcionam com outros periféricos.; 19/09/2023 16:41:57 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 19/09/2023 15:05:00; SOLUÇÃO DO CHAMADO: Em contato com a Sra. Germana, ela informou que “alguém” havia contactado ela e que conseguiu colocar pra funcionar e que poderia cancelar a solicitação. (CLEBER GONZAGA FRANCO); 19/09/2023 16:41:57 Utilização de serviços e peças: . (CLEBER GONZAGA FRANCO)",
    DESCRICAO: "Manutenção Solicitada: Scanner de Mesa  PIB: 3004388...",
    SOLUCAO:
      "Em contato com a Sra. Germana, ela informou que “alguém” havia contactado ela e que conseguiu colocar pra funcionar e que poderia cancelar a solicitação",
    TECNICO: "28128875833",
    NOME_TECNICO: "CLEBER GONZAGA FRANCO",
    SLA: 2,
    FECHAMENTO_OS: "19/09/2023 15:06:00",
    ATRASO: "0",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "JOAO PESSOA              ",
    AREA_CLASSIFICACAO: "PP",
    TP_ATENDIMENTO: "S",
    LIMITE_SLA: null,
  },
  {
    OS: "18534661",
    ABERTURA_OS: "21/09/2023 10:45:15",
    ATRIBUICAO_OS: "21/09/2023 10:51:39",
    PIB: "22060568",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "JAC00584                 ",
    MCU: "    00436793",
    ORGAO: "ASS JURIDICA MS/GCAJ",
    DR: "22",
    DR_SIGLA: "MS ",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 22060568 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: Scanner não esta ligando. Já foi testado em outras tomadas. Telefone de contato: 6733012157  Local de atendimento: ASJUR/SE/MS - AVENIDA CALÓGERAS , 2309, 2º PISO CEP 79002-900 - EDIFICIO SEDE -CENTRO -CAMPO GRANDE -MS Informe a localidade para atendimento desta solicitação: SE/MS",
    DESCRICAO_LONGA_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 22060568 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: Scanner não esta ligando. Já foi testado em outras tomadas. Telefone de contato: 6733012157  Local de atendimento: ASJUR/SE/MS - AVENIDA CALÓGERAS , 2309, 2º PISO CEP 79002-900 - EDIFICIO SEDE -CENTRO -CAMPO GRANDE -MS Informe a localidade para atendimento desta solicitação: SE/MS; 03/10/2023 16:04:42 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 22/09/2023 09:30:00; SOLUÇÃO DO CHAMADO: Scanner com problema na fonte de alimentação, enviamos uma fonte nova dia 21/09/23, numero de objeto TI 307 382 506 BR, onde a fonte foi entregue dia 22/09/23.. (CLEBER GONZAGA FRANCO); 03/10/2023 16:04:42 Utilização de serviços e peças: . (CLEBER GONZAGA FRANCO); 03/10/2023 16:05:03 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 22/09/2023 09:30:00; SOLUÇÃO DO CHAMADO: Scanner com problema na fonte de alimentação, enviamos uma fonte nova dia 21/09/23, numero de objeto TI 307 382 506 BR, onde a fonte foi entregue dia 22/09/23.. (CLEBER GONZAGA FRANCO); 03/10/2023 16:05:03 Utilização de serviços e peças: . (CLEBER GONZAGA FRANCO); 03/10/2023 16:05:29 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 22/09/2023 09:30:00; SOLUÇÃO DO CHAMADO: Scanner com problema na fonte de alimentação, enviamos uma fonte nova dia 21/09/23, numero de objeto TI 307 382 506 BR, onde a fonte foi entregue dia 22/09/23.. (CLEBER GONZAGA FRANCO); 03/10/2023 16:05:29 Utilização de serviços e peças: . (CLEBER GONZAGA FRANCO); 03/10/2023 16:05:39 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 22/09/2023 09:30:00; SOLUÇÃO DO CHAMADO: Scanner com problema na fonte de alimentação, enviamos uma fonte nova dia 21/09/23, numero de objeto TI 307 382 506 BR, onde a fonte foi entregue dia 22/09/23.. (CLEBER GONZAGA FRANCO); 03/10/2023 16:05:39 Utilização de serviços e peças: . (CLEBER GONZAGA FRANCO)",
    DESCRICAO: "Manutenção Solicitada: Scanner de Mesa  PIB: 2206056...",
    SOLUCAO:
      "Scanner com problema na fonte de alimentação, enviamos uma fonte nova dia 21/09/23, numero de objeto TI 307 382 506 BR, onde a fonte foi entregue dia 22/09/23.",
    TECNICO: null,
    NOME_TECNICO: null,
    SLA: 2,
    FECHAMENTO_OS: "22/09/2023 09:31:00",
    ATRASO: "0",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "CAMPO GRANDE             ",
    AREA_CLASSIFICACAO: "GA",
    TP_ATENDIMENTO: "S",
    LIMITE_SLA: null,
  },
  {
    OS: "18577280",
    ABERTURA_OS: "03/10/2023 15:30:16",
    ATRIBUICAO_OS: "03/10/2023 15:32:24",
    PIB: "18064315",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "JAC01640                 ",
    MCU: "    00436357",
    ORGAO: "SEC DE BENS MOVEIS/CPAS",
    DR: "18",
    DR_SIGLA: "MA ",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      'Manutenção Solicitada: Scanner de Mesa  PIB: 18064315 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: SCANNER APRESENTA MENSAGEM DE "NÃO RECONHECIDO", OU TRAVA A FOLHA NO APARELHO. FORAM ABERTAS 02 ORDENS DE SERVIÇO. E APÓS 02 REINSTALAÇÕES REMOTAMENTE, O SCANNER SÓ FUNCIONA POR ALGUM MOMENTO E VOLTA A TRAVAR Telefone de contato: 21072398 Local de atendimento: RUA JORGE DAMOU, 257, IVAR SALDANHA Informe a localidade para atendimento desta solicitação: SE/MA',
    DESCRICAO_LONGA_TOTAL:
      'Manutenção Solicitada: Scanner de Mesa  PIB: 18064315 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: SCANNER APRESENTA MENSAGEM DE "NÃO RECONHECIDO", OU TRAVA A FOLHA NO APARELHO. FORAM ABERTAS 02 ORDENS DE SERVIÇO. E APÓS 02 REINSTALAÇÕES REMOTAMENTE, O SCANNER SÓ FUNCIONA POR ALGUM MOMENTO E VOLTA A TRAVAR Telefone de contato: 21072398 Local de atendimento: RUA JORGE DAMOU, 257, IVAR SALDANHA Informe a localidade para atendimento desta solicitação: SE/MA; 11/10/2023 13:52:18 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 10/10/2023 08:28:00; SOLUÇÃO DO CHAMADO: Troca do equipamento através de logística reversa.. (JÉSSICA LIMA DA SILVA LARA); 11/10/2023 13:52:18 Utilização de serviços e peças: . (JÉSSICA LIMA DA SILVA LARA)',
    DESCRICAO: "Manutenção Solicitada: Scanner de Mesa  PIB: 1806431...",
    SOLUCAO: "Troca do equipamento através de logística reversa.",
    TECNICO: null,
    NOME_TECNICO: null,
    SLA: 2,
    FECHAMENTO_OS: "10/10/2023 08:29:00",
    ATRASO: "3",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "SAO LUIS                 ",
    AREA_CLASSIFICACAO: "PP",
    TP_ATENDIMENTO: "L",
    LIMITE_SLA: null,
  },
  {
    OS: "18636371",
    ABERTURA_OS: "19/10/2023 16:20:10",
    ATRIBUICAO_OS: "19/10/2023 16:27:51",
    PIB: "20449835",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "JAC02123                 ",
    MCU: "    00435689",
    ORGAO: "SEC ADMINISTRATIVA/GEVEN",
    DR: "20",
    DR_SIGLA: "MG ",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 20449835 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: SCANNER NA MESA DA LUCE NÃO ESTÁ PUXANDO AS FOLHA INDIVIDUALMENTE, PUXA TODAS AS FOLHAS AO MESMO TEMPO. Telefone de contato: 34310933/34310932 Local de atendimento: Av. Isabel Bueno, 442 Jaraguá-BH-MG Informe a localidade para atendimento desta solicitação: SE/MG   #####DIAGNOSTICO##### Verificado junto a usuária Luce que o scanner está puxando várias folhas ao mesmo tempo  Feitos os seguintes procedimentos:  - Feito verificação visual se existia alguma coisa impedindo a passagem do papel, sem sucesso  - Feito limpeza nos roletes do tracionador de papel, sem sucesso;  - Desinstalado o programa do scanner, sem sucesso.   Favor encaminhar para equipe de Hardware",
    DESCRICAO_LONGA_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 20449835 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: SCANNER NA MESA DA LUCE NÃO ESTÁ PUXANDO AS FOLHA INDIVIDUALMENTE, PUXA TODAS AS FOLHAS AO MESMO TEMPO. Telefone de contato: 34310933/34310932 Local de atendimento: Av. Isabel Bueno, 442 Jaraguá-BH-MG Informe a localidade para atendimento desta solicitação: SE/MG   #####DIAGNOSTICO##### Verificado junto a usuária Luce que o scanner está puxando várias folhas ao mesmo tempo  Feitos os seguintes procedimentos:  - Feito verificação visual se existia alguma coisa impedindo a passagem do papel, sem sucesso  - Feito limpeza nos roletes do tracionador de papel, sem sucesso;  - Desinstalado o programa do scanner, sem sucesso.   Favor encaminhar para equipe de Hardware; 27/10/2023 10:42:30 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 23/10/2023 17:57:00; SOLUÇÃO DO CHAMADO: Troca do equipamento através de logística reversa.. (CAMILA APARECIDA ARAUJO MORAIS); 27/10/2023 10:42:30 Utilização de serviços e peças: . (CAMILA APARECIDA ARAUJO MORAIS)",
    DESCRICAO: "Manutenção Solicitada: Scanner de Mesa  PIB: 2044983...",
    SOLUCAO: "Troca do equipamento através de logística reversa.",
    TECNICO: null,
    NOME_TECNICO: null,
    SLA: 2,
    FECHAMENTO_OS: "23/10/2023 17:58:00",
    ATRASO: "0",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "BELO HORIZONTE           ",
    AREA_CLASSIFICACAO: "GA",
    TP_ATENDIMENTO: "L",
    LIMITE_SLA: null,
  },
  {
    OS: "18724442",
    ABERTURA_OS: "13/11/2023 17:05:13",
    ATRIBUICAO_OS: "13/11/2023 18:09:00",
    PIB: "72403559",
    EQUIPAMENTO: "SCANNER POLICROMATICO",
    N_SERIE: "21JAC01294",
    MCU: "    00431134",
    ORGAO: "CTCE VILA MARIA/GTURN2",
    DR: "72",
    DR_SIGLA: "SPM",
    VALUE2: "000769_2023_001",
    SX_CONTRATO: "000769_2023_001 - ECSTEC                                  ",
    DESCRICAO_TOTAL:
      "Verificado junta com a usuária que a fonte do scanner esta intermintente, ora funciona, ora não.   Favor encaminhar para equipe de hardware  Telefone de contato: (11)21556859  PIB: 72403559 ",
    DESCRICAO_LONGA_TOTAL:
      "Manutenção Solicitada: Scanner de Mesa  PIB: 72403559 Nome: SCANNER POLICROMATICO          Modelo: DR-C230 / CANON                Marca: CANON                          Descreva a manutenção: Boa tarde! Solicito verifica a fonte de energia que alimenta o scanner citado, pois esta com mal contato. O mesmo encontra-se na Sala da gerência de turnos área operacional. Telefone de contato: (11)21556859 Local de atendimento: Av. Morvan Dias de Figueiredo 5845, Vila Maria - São Paulo - SP - CEP 02170-970 Informe a localidade para atendimento desta solicitação: SE/SPM   #####DIAGNOSTICO##### 13/11/2023 16:54:26, 09160935731,   Verificado junta com a usuária que a fonte do scanner esta intermintente, ora funciona, ora não.   Favor encaminhar para equipe de hardware; 13/11/2023 18:09:28 INFO. ADIC.: Verificado junta com a usuária que a fonte do scanner esta intermintente, ora funciona, ora não.   Favor encaminhar para equipe de hardware  Telefone de contato: (11)21556859  PIB: 72403559 . (89192133); 13/11/2023 18:09:28 ME: Encaminhado para contratada. (89192133); 16/11/2023 17:37:36 INFO. ADIC.: CHAMADO FECHADO - INSERIDO DATA DE FIM DE SERVIÇO (MU): 16/11/2023 17:39:06; SOLUÇÃO DO CHAMADO: Realizado a troca do cabo de energia que liga na fonte. (Genilson Vasconcellos Paiva); 16/11/2023 17:37:36 Utilização de serviços e peças: . (Genilson Vasconcellos Paiva)",
    DESCRICAO: "Verificado junta com a usuária que a fonte do scanne...",
    SOLUCAO: "Realizado a troca do cabo de energia que liga na fonte",
    TECNICO: "12958587894",
    NOME_TECNICO: "GENILSON VASCONCELLOS PAIVA",
    SLA: 2,
    FECHAMENTO_OS: "16/11/2023 17:40:06",
    ATRASO: "0",
    ESTADO: "ATESTADO",
    cae_qt_reabertura: 0,
    cae_tx_data_reabertura: null,
    CIDADE: "SAO PAULO                    ",
    AREA_CLASSIFICACAO: "GA",
    TP_ATENDIMENTO: "S",
    LIMITE_SLA: null,
  },
]
const dbUrl = "http://localhost:6001/api/chamados"
const postCorreiosdata = async () => {
  try {
    axios.post(dbUrl, data)
    console.log("os dados estão na nossa base de dados")
  } catch (error) {
    console.log("não foi possivel enviar os dados =>", error)
  }
}

postCorreiosdata()
